apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOps_servis2
  labels:
    app: DevOps_servis2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DevOps_servis2
  template:
    metadata:
      labels:
        app: DevOps_servis2
    spec:
      containers:
      - name: DevOps_servis2
        image: /repository/docker/spikoana1/servis2
     env:
        - name: SERVICE1_URL
          value: "http://138.197.60.41:80"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
